In [1]:
from sklearn.datasets import load_breast_cancer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [2]:
X,y  = load_breast_cancer(return_X_y=True)

In [3]:
X

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]], shape=(569, 30))

In [4]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [5]:
mgpipe = Pipeline(steps=[('scaler',StandardScaler())],verbose=True)

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X,y,shuffle=True,test_size=.2)

In [7]:
X_train

array([[1.174e+01, 1.402e+01, 7.424e+01, ..., 8.290e-02, 3.101e-01,
        6.688e-02],
       [1.025e+01, 1.618e+01, 6.652e+01, ..., 9.744e-02, 2.608e-01,
        9.702e-02],
       [1.705e+01, 1.908e+01, 1.134e+02, ..., 2.543e-01, 3.109e-01,
        9.061e-02],
       ...,
       [1.343e+01, 1.963e+01, 8.584e+01, ..., 1.160e-01, 2.884e-01,
        7.371e-02],
       [1.462e+01, 2.402e+01, 9.457e+01, ..., 6.946e-02, 2.522e-01,
        7.246e-02],
       [1.334e+01, 1.586e+01, 8.649e+01, ..., 1.708e-01, 3.527e-01,
        1.016e-01]], shape=(455, 30))

In [8]:
X_train[0]

array([1.174e+01, 1.402e+01, 7.424e+01, 4.273e+02, 7.813e-02, 4.340e-02,
       2.245e-02, 2.763e-02, 2.101e-01, 6.113e-02, 5.619e-01, 1.268e+00,
       3.717e+00, 3.783e+01, 8.034e-03, 1.442e-02, 1.514e-02, 1.846e-02,
       2.921e-02, 2.005e-03, 1.331e+01, 1.826e+01, 8.470e+01, 5.337e+02,
       1.036e-01, 8.500e-02, 6.735e-02, 8.290e-02, 3.101e-01, 6.688e-02])

In [10]:
mgpipe.fit_transform(X_train[0].reshape(-1,1))

[Pipeline] ............ (step 1 of 1) Processing scaler, total=   0.0s


array([[-0.24140503],
       [-0.2224189 ],
       [ 0.27904819],
       [ 3.21906761],
       [-0.33851636],
       [-0.33880556],
       [-0.33898002],
       [-0.33893688],
       [-0.33741741],
       [-0.33865792],
       [-0.33448788],
       [-0.32860801],
       [-0.30821457],
       [-0.02414704],
       [-0.33910007],
       [-0.33904689],
       [-0.33904089],
       [-0.33901325],
       [-0.33892373],
       [-0.33915027],
       [-0.22833125],
       [-0.18711135],
       [ 0.36615124],
       [ 4.10508717],
       [-0.33830426],
       [-0.33845915],
       [-0.33860613],
       [-0.33847664],
       [-0.33658469],
       [-0.33861004]])

In [11]:
X_train

array([[1.174e+01, 1.402e+01, 7.424e+01, ..., 8.290e-02, 3.101e-01,
        6.688e-02],
       [1.025e+01, 1.618e+01, 6.652e+01, ..., 9.744e-02, 2.608e-01,
        9.702e-02],
       [1.705e+01, 1.908e+01, 1.134e+02, ..., 2.543e-01, 3.109e-01,
        9.061e-02],
       ...,
       [1.343e+01, 1.963e+01, 8.584e+01, ..., 1.160e-01, 2.884e-01,
        7.371e-02],
       [1.462e+01, 2.402e+01, 9.457e+01, ..., 6.946e-02, 2.522e-01,
        7.246e-02],
       [1.334e+01, 1.586e+01, 8.649e+01, ..., 1.708e-01, 3.527e-01,
        1.016e-01]], shape=(455, 30))

In [12]:
scaler = StandardScaler()

In [14]:
scaler.fit_transform(X_train[0].reshape(-1,1))

array([[-0.24140503],
       [-0.2224189 ],
       [ 0.27904819],
       [ 3.21906761],
       [-0.33851636],
       [-0.33880556],
       [-0.33898002],
       [-0.33893688],
       [-0.33741741],
       [-0.33865792],
       [-0.33448788],
       [-0.32860801],
       [-0.30821457],
       [-0.02414704],
       [-0.33910007],
       [-0.33904689],
       [-0.33904089],
       [-0.33901325],
       [-0.33892373],
       [-0.33915027],
       [-0.22833125],
       [-0.18711135],
       [ 0.36615124],
       [ 4.10508717],
       [-0.33830426],
       [-0.33845915],
       [-0.33860613],
       [-0.33847664],
       [-0.33658469],
       [-0.33861004]])

In [18]:
import joblib

joblib.dump(scaler,"s0.pkl")

['s0.pkl']

In [19]:
re_scaler = joblib.load('s0.pkl')

In [20]:
X_train

array([[1.174e+01, 1.402e+01, 7.424e+01, ..., 8.290e-02, 3.101e-01,
        6.688e-02],
       [1.025e+01, 1.618e+01, 6.652e+01, ..., 9.744e-02, 2.608e-01,
        9.702e-02],
       [1.705e+01, 1.908e+01, 1.134e+02, ..., 2.543e-01, 3.109e-01,
        9.061e-02],
       ...,
       [1.343e+01, 1.963e+01, 8.584e+01, ..., 1.160e-01, 2.884e-01,
        7.371e-02],
       [1.462e+01, 2.402e+01, 9.457e+01, ..., 6.946e-02, 2.522e-01,
        7.246e-02],
       [1.334e+01, 1.586e+01, 8.649e+01, ..., 1.708e-01, 3.527e-01,
        1.016e-01]], shape=(455, 30))

In [21]:
re_scaler.transform(X_train[0].reshape(-1,1))

array([[-0.24140503],
       [-0.2224189 ],
       [ 0.27904819],
       [ 3.21906761],
       [-0.33851636],
       [-0.33880556],
       [-0.33898002],
       [-0.33893688],
       [-0.33741741],
       [-0.33865792],
       [-0.33448788],
       [-0.32860801],
       [-0.30821457],
       [-0.02414704],
       [-0.33910007],
       [-0.33904689],
       [-0.33904089],
       [-0.33901325],
       [-0.33892373],
       [-0.33915027],
       [-0.22833125],
       [-0.18711135],
       [ 0.36615124],
       [ 4.10508717],
       [-0.33830426],
       [-0.33845915],
       [-0.33860613],
       [-0.33847664],
       [-0.33658469],
       [-0.33861004]])